"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {api} from "@/http/api/api";
import {privateApi} from "@/http/api/privateApi";
import {toast} from "sonner";
import {Suspense} from "react";
const questions = [{"id":"roast-1","text":"साथीले ‘5 मिनेटमा आइपुग्छु’ भन्यो। तिमी के गर्छौ?","options":["गेटमा गएर कुरेर बस्छु 🤡","नेपाली टाइम हो, आरामले सुत्छु 😎","हरेक 2 मिनेटमा फोन गर्छु 📞","म पनि ‘आइपुगेँ’ भन्दै ओछ्यानमै 😂"]},{"id":"roast-2","text":"साथीले ‘भोलि पक्का पैसा फिर्ता दिन्छु’ भन्यो। तिमी के गर्छौ?","options":["भोलि आउँछ भनेर अर्को ऋण लिन्छु 😭","पैसा होइन, साथी गुमाएँ 🤣","पहिलेको 500 त दे भन्छु 💀","उसको बुबालाई QR पठाउँछु 😂"]},{"id":"roast-3","text":"Crush ले 3 दिनपछि ‘Sorry, busy थिएँ’ भन्यो। के गर्छौ?","options":["‘केही छैन माया’ भन्दै reply 🥹","3 दिनपछि reply दिन alarm 😎","Screenshot पठाएर emergency meeting 😂","‘कुन देशको प्रधानमन्त्री हो?’ 💀"]},{"id":"roast-4","text":"साथीले पार्टी दिन्छु भन्यो, बिल आउँदा फोनमा व्यस्त भयो। के गर्छौ?","options":["फोन खोसेर QR scan गराउँछु 😂","आफैँ तिरेर घर गएपछि रुन्छु 😭","Waiter लाई उसैलाई देखाउँछु 🤣","म पनि फोन आएको नाटक गर्छु 🏃"]},{"id":"roast-5","text":"साथीले ‘तेरो बारेमा कुरा सुनेको छु’ भन्यो तर बताउँदैन। के गर्छौ?","options":["आफ्ना सबै पाप सम्झिन्छु 😭","50 पटक ‘भन् न’ भन्छु 🤡","‘मैले पनि तेरो सुनेको छु’ 😎","FBI investigation सुरु गर्छु 🕵️"]},{"id":"roast-6","text":"साथीले ‘पैसा हाल, महिनामा double’ भन्यो। के गर्छौ?","options":["जग्गा बेचेर करोडपति सपना 🤡","पहिले उसको profit देखाउन भन्छु 😎","Billionaire tutorial हेर्छु 😂","मेरो tension double हुन्छ 💀"]},{"id":"roast-7","text":"लामो message पठायौ, उताबाट ‘हम्म’ आयो। के गर्छौ?","options":["अर्को 500 शब्द लेख्छु 😭","‘हम्म’ को अनुसन्धान गर्छु 🕵️","त्यसलाई पनि माया सम्झिन्छु 🤡","म पनि ‘ठ’ लेख्छु 😎"]},{"id":"roast-8","text":"साथीले भेट्न बोलाएर girlfriend को फोटो खिच्न लगायो। के गर्छौ?","options":["200 फोटो खिचेर photographer 📸","मलाई cameraman बनाउने? 😭","आँखा बन्द फोटो मात्र खिच्छु 😂","प्रति फोटो 100 रुपैयाँ माग्छु 💸"]},{"id":"roast-9","text":"साथीले ‘तेरो लागि जे पनि गर्छु’ भन्यो, 100 रुपैयाँ माग्यौ। के हुन्छ?","options":["Friendship पैसाभन्दा ठूलो lecture 🤣","उसैले 200 माग्छ 😭","उसको online status हराउँछ 💀","‘पैसा दिन्छु भनेको होइन’ 😂"]},{"id":"roast-10","text":"Important काम भन्दै बोलायो, TikTok खिच्न लगायो। के गर्छौ?","options":["50 take पछि पनि राम्रो भएन 😭","Camera उल्टो राख्छु 😂","Director fee 500 भन्छु 😎","आफैँ viral हुने TikTok बनाउँछु 🤣"]}];
type Answer = {question:string;selected:string};
type Attempt = {id:string;participantName:string;createdAt:string;score:number;answers:Answer[]};
type Challenge = {token:string;creatorName:string;createdAt:string;totalAttempts:number;attempts:Attempt[]};
function Main(){
 const params=useSearchParams();const token=params.get("c");
 const [name,setName]=useState("");const [creatorName,setCreatorName]=useState("");const [sender,setSender]=useState("");const [answers,setAnswers]=useState<Record<string,number>>({});const [step,setStep]=useState(0);
 const [result,setResult]=useState<{score:number;title:string}|null>(null);const [loading,setLoading]=useState(false);
 const [mine,setMine]=useState<Challenge[]>([]);const [mineError,setMineError]=useState(false);const [expanded,setExpanded]=useState("");
 const refresh=async()=>{try{const r=await privateApi.get("/friendcheck/roast/mine");setMine(r.data.data);setMineError(false)}catch{setMineError(true)}};
 useEffect(()=>{if(!token){void refresh();return;}void api.get("/friendcheck/roast/"+encodeURIComponent(token)).then(r=>setSender(r.data.data.creatorName||"साथी")).catch(()=>setSender("साथी"))},[token]);
 const link=(t:string)=>typeof window==="undefined"?"":window.location.origin+"/funny-check?c="+encodeURIComponent(t);
 const share=async(t:string,who:string)=>{const url=link(t);const message=who+" ले तिमीलाई Challenge गरेको छ! 🤣\\nओए साथी! 10 वटा funny प्रश्नको उत्तर देऊ। तिमीले के छान्यौ "+who+" ले हेर्न सक्छ 😂";try{if(navigator.share){await navigator.share({title:who+" ले तिमीलाई Challenge गरेको छ! 🤣",text:message,url});return}}catch{return}try{await navigator.clipboard.writeText(message+"\\n"+url);toast.success("Challenge message copied!")}catch{toast.error("Copy failed")}};
 const create=async()=>{setLoading(true);try{const r=await privateApi.post("/friendcheck/roast",{creatorName});await refresh();await share(r.data.data.token,creatorName)}catch{toast.error("Login गरेर फेरि प्रयास गर्नुहोस्")}finally{setLoading(false)}};
 const submit=async()=>{setLoading(true);try{const r=await api.post("/friendcheck/roast/"+encodeURIComponent(token!)+"/attempt",{participantName:name,answers});setResult(r.data.data)}catch{toast.error("Submit हुन सकेन, फेरि प्रयास गर्नुहोस्")}finally{setLoading(false)}};
 return <main className="mx-auto max-w-3xl space-y-5 p-4 md:p-8">
 <Link href="/invite-games" className="text-sm text-muted-foreground">← Back to games</Link>
 <header className="rounded-2xl bg-gradient-to-br from-amber-100 to-rose-100 p-6 text-center text-slate-900"><h1 className="text-3xl font-extrabold">🤣 तिमी कत्तिको चुतिया छौ?</h1><p className="mt-2">{token&&sender?sender+" ले तिमीलाई Challenge गरेको छ! 😂":"Funny Self-Check • 10 Questions • Just for Fun"}</p></header>
 {token ? result ? <section className="rounded-2xl border p-6 text-center"><p className="text-5xl font-black">{result.score}%</p><h2 className="mt-3 text-2xl font-bold">{result.title}</h2><p className="mt-3 text-sm text-muted-foreground">यो केवल रमाइलोका लागि हो, वास्तविक बुद्धि परीक्षण होइन।</p><Link className="mt-5 inline-block underline" href="/funny-check">आफ्ना साथीलाई पनि पठाऊ →</Link></section>
 : <section className="rounded-2xl border bg-card p-5 space-y-4">
 <p className="text-sm text-muted-foreground">तिम्रो नाम र छानेका सबै उत्तर challenge पठाउने साथीले हेर्न सक्छ। सहभागी हुनुअघि यो जानकारी बुझेर अगाडि बढ।</p>
 <label className="block text-sm font-semibold">तिम्रो नाम (optional)<input maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="जस्तै: Ram" className="mt-1 w-full rounded-lg border bg-background p-3"/></label>
 <p className="font-semibold">प्रश्न {step+1} / 10</p><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:((step+1)*10)+"%"}}/></div>
 <h2 className="text-xl font-bold">{questions[step].text}</h2>
 <div className="grid gap-2">{questions[step].options.map((option,i)=><button key={i} onClick={()=>setAnswers(a=>({...a,[questions[step].id]:i}))} className={"rounded-xl border p-3 text-left "+(answers[questions[step].id]===i?"border-primary bg-primary/10":"hover:bg-muted")}>{String.fromCharCode(65+i)}. {option}</button>)}</div>
 <div className="flex gap-2"><button disabled={step===0} onClick={()=>setStep(s=>s-1)} className="rounded-lg border px-4 py-3 disabled:opacity-40">Previous</button>{step<9?<button disabled={answers[questions[step].id]===undefined} onClick={()=>setStep(s=>s+1)} className="flex-1 rounded-lg bg-primary p-3 text-primary-foreground disabled:opacity-40">Next →</button>:<button disabled={loading||questions.some(q=>answers[q.id]===undefined)} onClick={submit} className="flex-1 rounded-lg bg-primary p-3 text-primary-foreground disabled:opacity-40">Submit & See Result 🤣</button>}</div>
 </section>
 : <section className="space-y-4"><div className="rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">📤 साथीलाई Share गर, उसले के छान्छ हेर!</h2><p className="mt-2 text-sm text-muted-foreground">Challenge link बनाऊ। साथीले login नगरी खेल्छ। उसले submit गरेपछि नाम (दिएमा), score र 10 वटै answer तिम्रो monitoring मा देखिन्छ।</p><label className="mt-4 block text-sm font-semibold">तिम्रो नाम<input value={creatorName} maxLength={60} onChange={e=>setCreatorName(e.target.value)} placeholder="जस्तै: Santosh" className="mt-1 w-full rounded-lg border bg-background p-3"/></label><button disabled={loading||!creatorName.trim()} onClick={create} className="mt-4 w-full rounded-xl bg-primary p-3 font-semibold text-primary-foreground disabled:opacity-50">Create & Share Challenge 🚀</button><p className="mt-2 text-xs text-muted-foreground">Monitoring हेर्न creator ले login गर्नुपर्छ।</p></div>
 <div className="rounded-2xl border bg-card p-5 space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">👀 Friend Answer Monitoring</h2><button className="rounded-lg border px-3 py-2 text-sm" onClick={refresh}>Refresh</button></div>
 {mineError?<p className="text-sm">Monitoring का लागि <Link className="underline" href="/auth/login">Login गर्नुहोस्</Link>।</p>:mine.length===0?<p className="text-sm text-muted-foreground">अहिलेसम्म कुनै challenge छैन।</p>:mine.map(ch=><div key={ch.token} className="rounded-xl border p-3 space-y-3"><div className="flex items-center justify-between gap-2"><div><p className="font-semibold">{ch.totalAttempts} friends played</p><p className="text-xs text-muted-foreground">{new Date(ch.createdAt).toLocaleString()}</p></div><button onClick={()=>share(ch.token,ch.creatorName)} className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">Share 🔗</button></div>{ch.attempts.map(a=><div key={a.id} className="rounded-lg bg-muted/50 p-3"><button className="flex w-full justify-between gap-2 text-left font-semibold" onClick={()=>setExpanded(expanded===a.id?"":a.id)}><span>{a.participantName} · {a.score}%</span><span>{expanded===a.id?"▲":"▼"}</span></button><p className="text-xs text-muted-foreground">{new Date(a.createdAt).toLocaleString()}</p>{expanded===a.id&&<div className="mt-3 space-y-3">{a.answers.map((v,i)=><div key={i}><p className="text-sm font-medium">{i+1}. {v.question}</p><p className="text-sm text-primary">→ {v.selected}</p></div>)}</div>}</div>)}</div>)}</div></section>}
 <p className="text-center text-xs text-muted-foreground">यो मजाकिया quiz हो। खेल्दा पैसा वा referral reward पाइँदैन।</p></main>;
}
export default function FunnyCheckPage(){return <Suspense fallback={<div className="p-8">Loading…</div>}><Main/></Suspense>}
