// Mock data for room rental app
export const mockRooms = [
  {
    id: "1",
    title: "Cozy Modern Apartment",
    address: "123 Oak Street",
    city: "San Francisco, CA",
    pricePerNight: 95,
    capacity: 2,
    roomType: "Apartment",
    latitude: 37.7749,
    longitude: -122.4194,
    rating: 4.9,
    reviews: 128,
    description:
      "Beautiful modern apartment in the heart of the city with stunning views",
    amenities: ["WiFi", "Kitchen", "AC", "Parking", "Washer/Dryer"],
    photos: [
      { url: "/modern-apartment-living-room.png" },
      { url: "/modern-apartment-bedroom.png" },
      { url: "/modern-apartment-kitchen.png" },
    ],
  },
  {
    id: "2",
    title: "Spacious Studio with Terrace",
    address: "456 Market Street",
    city: "San Francisco, CA",
    pricePerNight: 85,
    capacity: 2,
    roomType: "Studio",
    latitude: 37.7938,
    longitude: -122.3969,
    rating: 4.7,
    reviews: 95,
    description: "Bright studio with a private terrace overlooking the city",
    amenities: ["WiFi", "AC", "Terrace", "Kitchenette"],
    photos: [
      { url: "/studio-apartment-with-terrace.jpg" },
      { url: "/studio-interior-design.jpg" },
      { url: "/apartment-terrace-view.jpg" },
    ],
  },
  {
    id: "3",
    title: "Luxury One-Bedroom Suite",
    address: "789 Valencia Street",
    city: "San Francisco, CA",
    pricePerNight: 125,
    capacity: 2,
    roomType: "One-Bedroom",
    latitude: 37.7618,
    longitude: -122.4148,
    rating: 4.95,
    reviews: 156,
    description:
      "Premium one-bedroom suite with luxury amenities and personal concierge",
    amenities: [
      "WiFi",
      "Kitchen",
      "AC",
      "Parking",
      "Washer/Dryer",
      "Concierge",
      "Gym",
    ],
    photos: [
      { url: "/luxury-bedroom-suite.jpg" },
      { url: "/luxury-apartment-interior.png" },
      { url: "/luxury-bedroom-design.jpg" },
    ],
  },
  {
    id: "4",
    title: "Downtown Flat Near Transit",
    address: "321 Mission Street",
    city: "San Francisco, CA",
    pricePerNight: 75,
    capacity: 1,
    roomType: "Studio",
    latitude: 37.788,
    longitude: -122.398,
    rating: 4.6,
    reviews: 82,
    description:
      "Affordable flat close to public transit and downtown attractions",
    amenities: ["WiFi", "AC", "Kitchenette"],
    photos: [
      { url: "/downtown-apartment-studio.jpg" },
      { url: "/downtown-living-space.jpg" },
      { url: "/city-apartment-bedroom.png" },
    ],
  },
  {
    id: "5",
    title: "Charming Victorian House",
    address: "654 Haight Street",
    city: "San Francisco, CA",
    pricePerNight: 110,
    capacity: 3,
    roomType: "Entire House",
    latitude: 37.7708,
    longitude: -122.4468,
    rating: 4.85,
    reviews: 203,
    description:
      "Historic Victorian home with original architecture and modern upgrades",
    amenities: [
      "WiFi",
      "Kitchen",
      "Garden",
      "Parking",
      "Washer/Dryer",
      "Fireplace",
    ],
    photos: [
      { url: "/victorian-house-exterior.jpg" },
      { url: "/victorian-house-interior.jpg" },
      { url: "/victorian-house-garden.jpg" },
    ],
  },
  {
    id: "6",
    title: "Beachside Cottage",
    address: "987 Ocean Avenue",
    city: "San Francisco, CA",
    pricePerNight: 150,
    capacity: 4,
    roomType: "Cottage",
    latitude: 37.7597,
    longitude: -122.5107,
    rating: 4.92,
    reviews: 267,
    description: "Beautiful cottage right on the beach with private access",
    amenities: ["WiFi", "Kitchen", "AC", "Beach Access", "Parking", "Deck"],
    photos: [
      { url: "/beachside-cottage-exterior.jpg" },
      { url: "/beach-house-interior-cozy.jpg" },
      { url: "/beach-cottage-deck-view.jpg" },
    ],
  },
  {
    id: "7",
    title: "Mid-Century Modern Loft",
    address: "111 SOMA Street",
    city: "San Francisco, CA",
    pricePerNight: 115,
    capacity: 2,
    roomType: "Loft",
    latitude: 37.7722,
    longitude: -122.3974,
    rating: 4.8,
    reviews: 134,
    description:
      "Stunning mid-century modern loft with high ceilings and industrial charm",
    amenities: ["WiFi", "Kitchen", "AC", "Parking", "Washer/Dryer"],
    photos: [
      { url: "/modern-loft-living-room-exposed-brick.jpg" },
      { url: "/loft-bedroom-high-ceiling.jpg" },
      { url: "/industrial-loft-design.jpg" },
    ],
  },
  {
    id: "8",
    title: "Garden Apartment with Patio",
    address: "222 North Beach",
    city: "San Francisco, CA",
    pricePerNight: 105,
    capacity: 2,
    roomType: "Apartment",
    latitude: 37.8063,
    longitude: -122.4132,
    rating: 4.7,
    reviews: 98,
    description:
      "Peaceful garden apartment with private patio and green surroundings",
    amenities: ["WiFi", "Kitchen", "AC", "Garden", "Patio", "Parking"],
    photos: [
      { url: "/garden-apartment-patio.jpg" },
      { url: "/apartment-with-garden-greenery.jpg" },
      { url: "/patio-seating-area.jpg" },
    ],
  },
];
