"use client";
import { useEffect, useState } from 'react';
import { privateApi } from '@/http/api/privateApi';
import { officeError } from '@/http/services/office.service';
import { PhoneReveal } from './PhoneReveal';
type Entry={id:string;service:string;name:string;phone:string;location:string;details:string;requirements?:{roomType:string;people:number;maxRent:number};createdAt:string};
export function ChatFormsInbox(){const [page,setPage]=useState(0);const [version,setVersion]=useState(0);const [forms,setForms]=useState<Entry[]>([]);const [total,setTotal]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
useEffect(()=>{let alive=true;setLoading(true);setError('');privateApi.get('/office/chat-forms',{params:{page}}).then(r=>{if(!alive)return;const data=r.data?.data||r.data;setForms(data.forms);setTotal(data.total);}).catch(e=>{if(alive)setError(officeError(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[page,version]);
return <section className="space-y-3"><div className="flex justify-between"><h2 className="font-bold">Chat forms ({total})</h2><button onClick={()=>setVersion(v=>v+1)} className="underline">Refresh</button></div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading…</p>:forms.length?forms.map(f=><article key={f.id} className="space-y-2 rounded-xl border bg-white p-4"><p className="font-semibold">{f.service} · {f.name}</p><PhoneReveal phone={f.phone} label="Client phone"/><p>{f.location}</p>{f.requirements&&<p>{f.requirements.roomType} · {f.requirements.people} people · up to Rs {f.requirements.maxRent}/month</p>}<p className="whitespace-pre-wrap text-sm">{f.details}</p><p className="text-xs text-slate-500">{new Date(f.createdAt).toLocaleString()}</p></article>):<p>No chat forms yet.</p>}<div className="flex gap-3"><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1}</span><button disabled={(page+1)*30>=total||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>;}
