"use client";
import { useEffect, useRef, useState } from 'react';
import { MatchedRoom, ReceptionClient, officeError, officeService } from '@/http/services/office.service';
import { ClientSidebar } from './ClientSidebar';
import { RoomDetails } from './RoomDetails';
import { OfficeVideo } from './OfficeVideo';

export function ClientRequirements({revision,onSaved,onHistory,onRequests}:{revision:number;onSaved:()=>void;onHistory:(phone:string)=>void;onRequests:(phone:string)=>void}) {
  const [client,setClient]=useState<ReceptionClient|null>(null);const [rooms,setRooms]=useState<MatchedRoom[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(0);const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const generation=useRef(0);
  useEffect(()=>{if(!client)return;const current=++generation.current;setLoading(true);setError('');setRooms([]);officeService.matchingRooms(search,client.id).then(r=>{if(current===generation.current){setRooms(r.rooms);setTotal(r.total);setPage(0);}}).catch(e=>{if(current===generation.current)setError(officeError(e));}).finally(()=>{if(current===generation.current)setLoading(false);});return()=>{generation.current+=1;};},[client,search,revision]);
  async function more(){if(!client||loading)return;const current=generation.current;setLoading(true);try{const r=await officeService.matchingRooms(search,client.id,page+1);if(current===generation.current){setRooms(prev=>[...prev,...r.rooms]);setPage(v=>v+1);}}catch(e){setError(officeError(e));}finally{setLoading(false);}}
  return <section className="grid items-start gap-4 lg:grid-cols-[minmax(0,380px)_1fr]"><ClientSidebar revision={revision} onSaved={onSaved} onView={c=>{setClient(c);setSearch('');setQuery('');}}/><div className="space-y-3"><h2 className="text-lg font-bold">Client Requirements</h2>{error&&<p role="alert" className="text-red-700">{error}</p>}{!client?<p>Select “Matching rooms” on a client to see ranked rooms.</p>:<><h3 className="font-semibold">Matching rooms ({total})</h3><p className="text-sm">Current rental ends: {client.requirements?.rentalEndsOn||'Not recorded'} · Moving: {client.requirements?.moveInDate||'Not recorded'} · Vehicle: {client.requirements?.vehicle||'NONE'}</p><button className="rounded-lg border px-3 py-2 text-sm" onClick={()=>onHistory(client.phone)}>Client history</button><button className="ml-2 rounded-lg border px-3 py-2 text-sm" onClick={()=>onRequests(client.phone)}>Booking requests</button><form className="flex gap-2" onSubmit={e=>{e.preventDefault();setSearch(query);}}><input className="min-w-0 flex-1 rounded-lg border p-2" aria-label="Search selected client's matching rooms" value={query} onChange={e=>setQuery(e.target.value)}/><button className="rounded-lg border px-3">Search</button></form>{loading&&<p>Loading…</p>}{!loading&&!rooms.length&&<p>मिल्ने room भेटिएन। Budget वा area परिवर्तन गर्नुहोस्।</p>}<div className="grid gap-3">{rooms.map((r,index)=><article key={r.id} className="overflow-hidden rounded-xl border bg-white p-3"><div className="mb-2 flex items-center justify-between"><span className="font-semibold">Matching room #{index+1}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-900">{r.score} match score</span></div><div className="grid items-start gap-4 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div className="min-w-0"><OfficeVideo roomId={r.id}/><RoomDetails room={r}/></div><div className="space-y-2 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold">Matching details</p>{r.reasons.map(reason=><p key={reason} className="text-emerald-800">✓ {reason}</p>)}{r.mismatches.map(reason=><p key={reason} className="text-amber-800">! {reason}</p>)}</div></div></article>)}</div>{rooms.length<total&&<button disabled={loading} className="rounded-lg border px-3 py-2" onClick={()=>void more()}>Load more rooms</button>}</>}</div></section>;
}
