"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { BookingFee, MatchedRoom, OfficeRequest, officeError, officeService } from '@/http/services/office.service';
import { MatchingFields, requirementsDraft, requirementsPayload } from './MatchingFields';
import { OfficeVideo } from './OfficeVideo';
import { RequestMessages } from './RequestMessages';

export function RequirementsPortal() {
  const [name,setName]=useState('');const [phone,setPhone]=useState('');const [notes,setNotes]=useState('');const [draft,setDraft]=useState(requirementsDraft());
  const [rooms,setRooms]=useState<MatchedRoom[]>([]);const [bookings,setBookings]=useState<OfficeRequest[]>([]);const [fee,setFee]=useState<BookingFee|null>(null);
  const [total,setTotal]=useState(0);const [page,setPage]=useState(0);const [saved,setSaved]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const pending=useRef(false);
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [chat,setChat]=useState<string|null>(null);
  const generation=useRef(0);
  useEffect(()=>{let alive=true;Promise.all([officeService.myRequirements(),officeService.fee(),officeService.myBookings()]).then(([r,f,b])=>{if(!alive)return;setName(r.client?.name||r.name);setPhone(r.client?.phone||r.phone);setNotes(r.client?.notes||'');setDraft(requirementsDraft(r.client?.requirements));setSaved(Boolean(r.client));setFee(f);setBookings(b);}).catch(e=>{if(alive)setError(officeError(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
  useEffect(()=>{if(!saved)return;const current=++generation.current;setLoading(true);officeService.matchingRooms(search).then(r=>{if(current===generation.current){setRooms(r.rooms);setTotal(r.total);setPage(0);}}).catch(e=>{if(current===generation.current)setError(officeError(e));}).finally(()=>{if(current===generation.current)setLoading(false);});return()=>{generation.current+=1;};},[saved,search]);
  const refreshBookings=useCallback(async()=>setBookings(await officeService.myBookings()),[]);
  async function act(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(officeError(e));}finally{pending.current=false;setBusy(false);}}
  function save(e:FormEvent){e.preventDefault();void act(async()=>{await officeService.saveMyRequirements({clientName:name,clientPhone:phone,notes,requirements:requirementsPayload(draft)});const r=await officeService.matchingRooms(search);setRooms(r.rooms);setTotal(r.total);setPage(0);setSaved(true);setNotice('Details saved. Suitable rooms are ranked below.');});}
  async function more(){if(loading)return;const current=generation.current;setLoading(true);try{const r=await officeService.matchingRooms(search,undefined,page+1);if(current===generation.current){setRooms(prev=>[...new Map([...prev,...r.rooms].map(x=>[x.id,x])).values()]);setTotal(r.total);setPage(v=>v+1);}}catch(e){setError(officeError(e));}finally{setLoading(false);}}
  return <section className="space-y-4 rounded-xl border bg-white p-4" aria-label="My client requirements"><h2 className="text-xl font-bold">New client details · Find matching rooms</h2>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-emerald-700">{notice}</p>}<details open={!saved}><summary className="cursor-pointer font-semibold">{saved?'Edit my room requirements':'Fill in my requirements'}</summary><form onSubmit={save} className="mt-3 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Name *<input required maxLength={180} className="mt-1 w-full rounded-lg border p-2.5" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm">Phone *<input required type="tel" maxLength={30} className="mt-1 w-full rounded-lg border p-2.5" value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><MatchingFields tenant value={draft} onChange={setDraft}/><label className="block text-sm">Additional requirements<textarea maxLength={5000} className="mt-1 w-full rounded-lg border p-2.5" value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={busy||loading} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-white disabled:opacity-50">{busy?'Saving…':'Save & show matching rooms'}</button></form></details>
    {fee&&<p className="rounded-lg bg-slate-50 p-3 text-sm">Service charge: {fee.amount===null?'Not configured':`Rs ${fee.amount}`} · {fee.purpose}. {fee.paymentAvailable?'Pay from your existing wallet after requesting.':'Online payment is unavailable until reception configures it.'}</p>}
    {saved&&<><form className="flex gap-2" onSubmit={e=>{e.preventDefault();setSearch(query);}}><input className="min-w-0 flex-1 rounded-lg border p-2" aria-label="Search my matching rooms" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search within suitable rooms"/><button className="rounded-lg border px-3">Search</button></form><h3 className="font-semibold">Suitable matching rooms ({total})</h3>{loading?<p>Loading matches…</p>:!rooms.length?<p>मिल्ने room भेटिएन। Budget वा preferred/alternative area परिवर्तन गर्नुहोस्।</p>:<div className="grid gap-3 md:grid-cols-2">{rooms.map(room=><article key={room.id} className="overflow-hidden rounded-xl border"><OfficeVideo roomId={room.id} recipient/><div className="space-y-2 p-3"><h4 className="font-semibold">{room.code} · {room.title}</h4><p className="text-sm">{room.location} · Rs {room.price}/month</p><ul className="list-disc pl-4 text-xs text-emerald-800">{room.reasons.map(r=><li key={r}>{r}</li>)}</ul>{room.mismatches.map(r=><p className="text-xs text-amber-800" key={r}>{r}</p>)}<button disabled={busy} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm text-white disabled:opacity-50" onClick={()=>void act(async()=>{const r=await officeService.book(room.id);await refreshBookings();setChat(r.id);setNotice('Booking request received. Reception will confirm separately.');})}>Request Booking / Message reception</button></div></article>)}</div>}{rooms.length<total&&<button disabled={loading} className="rounded-lg border px-3 py-2" onClick={()=>void more()}>Load more matching rooms</button>}</>}
    <section className="space-y-2"><div className="flex justify-between"><h3 className="font-semibold">My booking requests</h3><button disabled={busy} className="text-sm underline" onClick={()=>void act(refreshBookings)}>Refresh status</button></div>{bookings.map(b=><article key={b.id} className="space-y-2 rounded-lg border p-3 text-sm"><p className="font-semibold">{b.code} · {b.title}</p><p>Booking: {b.status} · Payment: {b.paymentStatus||'UNPAID'}</p><p>Service charge: {b.serviceCharge==null?'Not configured':`Rs ${b.serviceCharge}`}</p><div className="flex flex-wrap gap-2"><button className="rounded-lg border px-3 py-2" onClick={()=>setChat(b.id)}>Message reception</button>{b.paymentStatus!=='PAID'&&b.serviceCharge!=null&&fee?.paymentAvailable&&!['CANCELLED','CLOSED'].includes(b.status)&&<button disabled={busy} className="rounded-lg bg-emerald-700 px-3 py-2 text-white disabled:opacity-50" onClick={()=>{if(window.confirm(`Pay Rs ${b.serviceCharge} from your wallet for this booking service? This does not confirm tenancy.`))void act(async()=>{await officeService.pay(b.id);await refreshBookings();setNotice('Service charge paid. Booking confirmation remains separate.');});}}>Pay service charge</button>}<Link className="px-2 py-2 underline" href="/user/dashboard/wallet">Wallet / add funds</Link></div></article>)}{!bookings.length&&<p className="text-sm text-slate-500">No booking requests yet.</p>}</section>
    {chat&&<RequestMessages key={chat} requestId={chat} onClose={()=>setChat(null)}/>}</section>;
}
