"use client";
import { FormEvent, useEffect, useRef, useState } from 'react';
import { BookingMessage, officeError, officeService } from '@/http/services/office.service';
export function RequestMessages({requestId,onClose}:{requestId:string;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);const pending=useRef(false);
  const [messages,setMessages]=useState<BookingMessage[]>([]);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
  useEffect(()=>{const node=dialog.current;node?.showModal();let alive=true;officeService.messages(requestId).then(r=>{if(alive)setMessages(r);}).catch(e=>{if(alive)setError(officeError(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;node?.close();};},[requestId]);
  async function reload(){setLoading(true);setError('');try{setMessages(await officeService.messages(requestId));}catch(e){setError(officeError(e));}finally{setLoading(false);}}
  async function send(e:FormEvent){e.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await officeService.sendMessage(requestId,message);setMessage('');await reload();}catch(e){setError(officeError(e));}finally{pending.current=false;setBusy(false);}}
  return <dialog ref={dialog} className="max-h-[85vh] w-[calc(100%-1.5rem)] max-w-xl overflow-y-auto rounded-xl p-5 backdrop:bg-black/60" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="space-y-3"><div className="flex justify-between gap-3"><h2 className="font-bold">Booking messages</h2><button disabled={busy} onClick={onClose}>Close ✕</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}<button disabled={loading} className="text-sm underline" onClick={()=>void reload()}>Refresh messages</button>{loading&&<p role="status">Loading…</p>}{messages.map(m=><article key={m.id} className={`rounded-lg p-3 ${m.fromStaff?'bg-blue-50':'bg-slate-100'}`}><p className="text-xs text-slate-500">{m.senderName} · {m.fromStaff?'Reception':'Client'} · {new Date(m.createdAt).toLocaleString()}</p><p className="whitespace-pre-wrap text-sm">{m.message}</p></article>)}{!loading&&!messages.length&&<p className="text-sm text-slate-500">No messages yet.</p>}<form onSubmit={send} className="space-y-2"><label className="block text-sm">Message<textarea autoFocus required maxLength={5000} className="mt-1 w-full rounded-lg border p-3" value={message} onChange={e=>setMessage(e.target.value)}/></label><button disabled={busy||!message.trim()} className="rounded-lg bg-emerald-700 px-4 py-2 text-white disabled:opacity-50">{busy?'Sending…':'Send message'}</button></form></div></dialog>;
}
