"use client";
import {useEffect,useState} from 'react';
import {officeService,officeError} from '@/http/services/office.service';
import type {ReceptionClient,MatchedRoom} from '@/http/services/office.service';
import {PhoneReveal} from './PhoneReveal';
export function SavedClients({revision,onEdit}:{revision:number;onEdit?:(client:ReceptionClient)=>void}){
 const [clients,setClients]=useState<ReceptionClient[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[selected,setSelected]=useState<string|null>(null),[matches,setMatches]=useState<MatchedRoom[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[suggested,setSuggested]=useState<MatchedRoom[]>([]),[nearbyLoading,setNearbyLoading]=useState(false);
 useEffect(()=>{let active=true;officeService.clients().then(r=>{if(!active)return;setClients(r.clients);r.clients.forEach(c=>officeService.matchingRooms('',c.id).then(m=>{if(active)setCounts(v=>({...v,[c.id]:m.total}));}).catch(()=>{}));}).catch(e=>{if(active)setError(officeError(e));});return()=>{active=false;};},[revision]);
 async function view(c:ReceptionClient){if(selected===c.id){setSelected(null);return;}setSelected(c.id);setLoading(true);setMatches([]);setSuggested([]);try{const r=await officeService.matchingRooms('',c.id);setMatches(r.rooms);setCounts(v=>({...v,[c.id]:r.total}));setNearbyLoading(true);const area=(c.requirements?.area||'').trim().toLowerCase();const city=(c.requirements?.city||'').trim().toLowerCase();if(area||city){const other=await officeService.rooms('', 'AVAILABLE',0);const ids=new Set(r.rooms.map(room=>room.id));setSuggested(other.rooms.filter(room=>!ids.has(room.id)&&((area&&room.location.toLowerCase().includes(area))||(city&&room.location.toLowerCase().includes(city)))).slice(0,6).map(room=>({...room,reasons:[],mismatches:[],score:0})));}}catch(e){setError(officeError(e));}finally{setLoading(false);setNearbyLoading(false);}}
 return <section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="text-xl font-bold">Saved Clients ({clients.length})</h2><p className="text-xs text-slate-500">Saved to Reception database. Matching counts update when rooms are added.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{clients.map(c=><article key={c.id} className="rounded-xl border p-3"><div className="flex items-center gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-slate-200 font-bold" aria-label="No client photo available">{c.name?.charAt(0).toUpperCase()||'?'}</div><div className="min-w-0 flex-1"><p className="font-semibold">{c.name}</p><PhoneReveal phone={c.phone} label="Client phone"/><p className="text-xs">{c.requirements?.city||'Any city'}</p></div><button type="button" className="rounded-lg bg-blue-50 p-2 text-xs font-bold text-blue-800" onClick={()=>void view(c)}>Matched Rooms <span className="mt-1 block rounded bg-blue-700 p-1 text-lg text-white">{counts[c.id]??'…'}</span></button></div>{onEdit&&<button type="button" className="mt-2 rounded-lg border px-3 py-2 text-sm font-semibold" onClick={()=>onEdit(c)}>Edit Client Details</button>}{selected===c.id&&<div className="mt-3 space-y-2 border-t pt-3">{loading&&<p>Loading matches…</p>}{!loading&&<p className="font-semibold text-blue-700">{counts[c.id]??matches.length} matching rooms</p>}{!loading&&matches.length===0&&<p>0 matched rooms. Try editing location, room type or budget.</p>}{matches.map(r=><div key={r.id} className="rounded-lg border p-3"><p className="font-semibold">{r.title} · {r.code}</p><p>{r.location} · Rs. {Number(r.price).toLocaleString('en-US')}</p>{r.reasons?.map((v,i)=><p key={i} className="text-xs text-emerald-700">✓ {v}</p>)}{r.mismatches?.map((v,i)=><p key={i} className="text-xs text-amber-700">! {v}</p>)}</div>)}<div className="mt-4 border-t pt-3"><h3 className="font-bold">Suggested Rooms · Nearby Area</h3><p className="text-xs text-slate-500">Other available rooms in the same named area or city, not exact matches. Distance is not verified.</p>{nearbyLoading&&<p>Checking nearby rooms…</p>}{!nearbyLoading&&suggested.length===0&&<p className="text-sm text-slate-500">No additional rooms found in this area.</p>}{suggested.map(room=><div key={room.id} className="mt-2 rounded-lg border bg-amber-50 p-3"><p className="font-semibold">{room.title} · {room.code}</p><p className="text-sm">{room.location} · Rs. {Number(room.price).toLocaleString("en-US")}</p><p className="text-xs text-amber-800">Nearby suggestion · Not a confirmed match</p></div>)}</div></div>}</article>)}</section>;
}
export function RoomMatchedClients({roomId,revision}:{roomId:string;revision:number}){
 const [total,setTotal]=useState<number|null>(null),[clients,setClients]=useState<ReceptionClient[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>{let active=true;officeService.matchingClients(roomId).then(r=>{if(active){setTotal(r.total);setClients(r.clients);}}).catch(()=>{});return()=>{active=false;};},[roomId,revision]);
 return <div className="border-t p-3"><button type="button" className="flex w-full items-center justify-between rounded-lg bg-blue-50 p-2 font-semibold text-blue-800" onClick={()=>setOpen(v=>!v)}>Matched Clients <span className="rounded-md bg-blue-700 px-3 py-1 text-lg text-white">{total??'—'}</span></button>{open&&<div className="mt-2 space-y-2">{clients.length===0&&<p className="text-sm">No matched clients yet.</p>}{clients.map(c=><div key={c.id} className="rounded-lg border p-2"><div className="flex items-center gap-2"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-200 font-bold" aria-label="No client photo available">{c.name?.charAt(0).toUpperCase()||'?'}</span><div><p className="font-semibold">{c.name}</p><PhoneReveal phone={c.phone} label="Client phone"/></div></div>{c.reasons?.map((v,i)=><p key={i} className="text-xs text-emerald-700">✓ {v}</p>)}{c.mismatches?.map((v,i)=><p key={i} className="text-xs text-amber-700">! {v}</p>)}</div>)}</div>}</div>;
}