"use client";
import { FormEvent, useEffect, useState } from 'react';
import { officeService, officeBackend, officeError, OfficeRoom } from '@/http/services/office.service';

export function SharedRoom({ token }: { token: string }) {
  const [room,setRoom]=useState<OfficeRoom|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({name:'',phone:'',message:''});
  useEffect(()=>{let alive=true;officeService.shared(token).then(r=>{if(alive)setRoom(r);}).catch(e=>{if(alive)setError(officeError(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[token]);
  async function submit(e: FormEvent) { e.preventDefault();setBusy(true);setError('');try{await officeService.request(token,form);setNotice('Request received. Reception will contact you.');}catch(e){setError(officeError(e));}finally{setBusy(false);} }
  return <main className="min-h-screen bg-slate-100 px-3 py-8 text-slate-900"><div className="mx-auto max-w-3xl space-y-5"><div><p className="text-sm font-semibold text-emerald-700">RoomKhoj · Office</p><h1 className="text-2xl font-bold">Your shared room</h1></div>{loading?<p>Loading room…</p>:!room?<div className="rounded-xl bg-white p-8"><p role="alert">This link has expired, has been revoked, or the room is no longer available.</p></div>:<><article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><video controls playsInline preload="none" className="aspect-video w-full bg-black" src={`${officeBackend}/office/shared/${encodeURIComponent(token)}/video`} onError={()=>setError('Could not play this video. The link may have expired; contact reception. Browser-compatible MP4 works best.')}/><div className="space-y-3 p-5"><div className="flex justify-between gap-3"><h2 className="text-2xl font-bold">{room.title}</h2><span className="rounded-lg bg-emerald-50 p-2 font-mono font-bold">{room.code}</span></div><p>📍 {room.location} · रु {Number(room.price).toLocaleString()}/month</p><p className="whitespace-pre-wrap">{room.details}</p><p>Owner: {room.ownerName} · <a className="underline" href={`tel:${room.ownerPhone}`}>{room.ownerPhone}</a></p>{room.tiktokUrl&&<a className="inline-block text-blue-700 underline" target="_blank" rel="noopener noreferrer" href={room.tiktokUrl}>Open TikTok ↗</a>}</div></article><form onSubmit={submit} className="space-y-4 rounded-2xl bg-white p-5"><h2 className="text-xl font-semibold">Request this room</h2>{notice?<p role="status" className="text-emerald-700">{notice}</p>:<><label className="block text-sm">Your name<input required maxLength={180} className="mt-1 w-full rounded-lg border p-3" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block text-sm">Phone number<input type="tel" required maxLength={30} className="mt-1 w-full rounded-lg border p-3" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="block text-sm">Message / preferred visit time<textarea maxLength={5000} className="mt-1 w-full rounded-lg border p-3" rows={3} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button disabled={busy} className="rounded-lg bg-emerald-700 px-5 py-3 text-white disabled:opacity-50">{busy?'Sending…':'Send room request'}</button></>}</form></>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}</div></main>;
}
